name: ci
on: [push, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - name: Install pylint
      run: |
        sudo apt update -y
        python -m pip install --upgrade pip
        pip install pylint
    - uses: pre-commit/action@v3.0.0
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - name: Install dependencies
      run: |
        sudo apt update -y
        sudo apt install -y libxml2 libxml2-dev libxslt1-dev
        python -m pip install --upgrade pip
        pip install pytest poetry lxml pyopenmensa deepl
    - name: Test with pytest
      run: pytest
      env:
        PYTHONPATH: src/
