name: swagger
on:
  push:
    branches:
      - master
    paths:
      - openapi.yml
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with:
          output: docs
          spec-file: openapi.yml
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          add-paths: docs
          delete-branch: true
          base: gh-pages
          title: '[gh-pages] Update swagger documentation'
          branch: create-pull-request/swagger
